engines:
  gofmt:
    enabled: true
  golint:
    enabled: true
  keepachangelog:
    enabled: true
    exclude_patterns:
      - "**"                # exclude all
      - "!CHANGELOG.md"
ratings:
  paths:
  - "**CHANGELOG.md"
